services:
  cloudflared:
    image: cloudflare/cloudflared@sha256:188bb03589a32affed3cf4d0590565ffe67b78866e6b5582574afab2b705bafe
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    depends_on:
      api:
        condition: service_healthy
      powersync:
        condition: service_healthy
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
